### ISSUE TITLE
Add ability to select all / toggle apps in a project

### ISSUE THREAD

**Issue by snickler** [JaneaSystems/PowerToys-DevProjects#50]
![image](https://github.com/JaneaSystems/PowerToys-DevProjects/assets/4016293/c9c0585f-d33e-4151-a29d-dcf7a86e106b)

Would like a select all just to either select all apps after unselecting, or just to unselect all and check a few applications.

**Comment by donlaci** [comment]
@plante-msft 
Any thoughts on this implementation?

![RIJvoYQtIZ](https://github.com/JaneaSystems/PowerToys-DevProjects/assets/57342539/1c81cbd1-b677-4211-a67c-82ae731f6898)

**Comment by SeraphimaZykova** [comment]
Closing this issue according to https://github.com/JaneaSystems/PowerToys-DevProjects/issues/67#issuecomment-2203962876
